from .rtkcmn import uGNSS

class GNSS_col():
    """ SAT matric to sys column """
    # GPS = [0, 100]
    # GLO = [100, 200]
    # BDS = [200, 300]
    # GAL = [300, 400]
    # QZS = [400, 500]
    # IRN = [500, 600]
    # SBS = [600, 700]

    GPS = [0, uGNSS.GPSMAX]
    GLO = [uGNSS.GPSMAX, uGNSS.GPSMAX+uGNSS.GLOMAX]
    BDS = [uGNSS.GPSMAX+uGNSS.GLOMAX, uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.BDSMAX]
    GAL = [uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.BDSMAX, uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.BDSMAX+uGNSS.GALMAX]
    QZS = [uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.GALMAX+uGNSS.BDSMAX, uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.GALMAX+uGNSS.BDSMAX+uGNSS.QZSMAX]
    SBS = [uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.GALMAX+uGNSS.BDSMAX+uGNSS.QZSMAX, uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.GALMAX+uGNSS.BDSMAX+uGNSS.QZSMAX+uGNSS.SBSMAX]
    IRN = [uGNSS.GPSMAX+uGNSS.GLOMAX+uGNSS.GALMAX+uGNSS.BDSMAX+uGNSS.QZSMAX+uGNSS.SBSMAX, uGNSS.MAXSAT]